applications/analytics/urls.py
from django.urls import path

from applications.analytics import views

urlpatterns = [
    path('registration-report/', views.RegistrationReport.as_view(), name='registration-report'),
    path('attendee-list/', views.PossibleAttendeesList.as_view(), name='attendees-list'),
    path('attendee/<slug:slug>', views.AttendeeProfile.as_view(), name='attendee-profile'),
    path('leaderboard', views.Leaderboard.as_view(), name='leaderboard'),
]

los30randomdema0/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', include(('applications.registration.urls', 'registration'), namespace='registration')),
    path('pokedex/', include(('applications.pokedex.urls', 'pokedex'), namespace='pokedex')),
    path('analytics/', include(('applications.analytics.urls', 'analytics'), namespace='analytics')),
    path('sakura/', include(('applications.sakura.urls', 'sakura'), namespace='sakura')),
    path('instagram/', include(('applications.instagram.urls', 'instagram'), namespace='instagram')),
]

applications/analytics/models.py
from django.db import models

# Create your models here.

applications/analytics/views.py
from faulthandler import is_enabled

import qrcode
import urllib.parse
from django.db.models import Count, Q
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.html import format_html
from django.views.generic import ListView, DetailView, TemplateView
from qrcode.image.svg import SvgPathImage

from applications.registration.models import Registration, PossibleAttendees, AttendeeToken
from applications.pokedex.models import Badge, Profile, Connection


# Create your views here.


@method_decorator(login_required, name='dispatch')
class RegistrationReport(ListView):
    template_name = 'analytics/registration_report.html'
    context_object_name = 'registrations'
    queryset = Registration.objects.all()


class PossibleAttendeesList(ListView):
    template_name = 'analytics/possible_attendees.html'
    context_object_name = 'possible_attendees'
    queryset = PossibleAttendees.objects.all()


class AttendeeProfile(DetailView):
    template_name = 'analytics/attendee_profile.html'
    context_object_name = 'attendee'
    queryset = PossibleAttendees.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['registration'] = Registration.objects.filter(possible_attendee=self.object).first()
        class CustomSvgPathImage(SvgPathImage):
            QR_PATH_STYLE = {
                "fill": "#ebecf0",
                "fill-opacity": "1",
                "fill-rule": "nonzero",
                "stroke": "none",
            }

        img = qrcode.make(self.object.slug, image_factory=CustomSvgPathImage, box_size=20)
        img_string = img.to_string(encoding='unicode')
        context['qr'] = format_html(img_string)
        context['profile'] = self.object.profile
        context['followers'] = Connection.objects.filter(followed=self.object.profile)
        context['following'] = Connection.objects.filter(follower=self.object.profile)
        context['total_active_profiles'] = Profile.objects.filter(
            # is_active=True,
            is_enabled=True
        ).count()
        token, created = AttendeeToken.objects.get_or_create(attendee=self.object)
        if created:
            token.generate_token()

        context['app_url'] = urllib.parse.quote_plus(f'https://app.los30randomdema0.com/token/{token.token}')
        return context

class Leaderboard(TemplateView):
    template_name = 'analytics/leaderboard.html'
    context_object_name = 'leaderboard'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        connections = Profile.objects.filter(
            ~Q(attendee__name='Ma0'),
            is_enabled=True,
            is_active=True,
        ).annotate(connections=Count('following')).filter(connections__gt=0).order_by('-connections')
        context['connections'] = connections
        cards = PossibleAttendees.objects.filter(
            ~Q(name='Ma0')
        ).annotate(
            cards=Count('captured_cards')
        ).filter(
            cards__gt=0
        ).order_by('-cards')
        context['cards'] = cards
        return context

applications/analytics/templates/analytics/attendee_profile.html
{% extends 'analytics/base.html' %}
{% block content %}
    <h1 class="title">Attendee Profile</h1>
    <div class="columns">
        <div class="column is-one-third">
            <figure class="image is-256x256">
                {% if attendee.profile_pic %}
                    <img src="{{ attendee.profile_pic.url }}" alt="{{ attendee.name }}">
                {% endif %}
            </figure>
            <div class="columns is-multiline is-centered" style="background: aliceblue">
                {% for badge in profile.badges.all %}
                    <div class="column">
                        <figure class="image is-32x32">
                            <img src="{{ badge.image.url }}" alt="{{ badge.name }}">
                        </figure>
                    </div>

                {% endfor %}
            </div>
        </div>

        <div class="column">
            <p><strong>Name:</strong> {{ attendee.name }}</p>
            <p><strong>Whatsapp:</strong> {{ attendee.phone }}</p>
            <p><strong>Instagram:</strong> {{ attendee.instagram }}</p>
            <p><strong>Vegetarian:</strong> {{ registration.get_vegetarian_display }}</p>
            <p><strong>Alcohol:</strong> {{ registration.get_alcohol_display }}</p>
            <p><strong>Weed:</strong> {{ registration.get_weed_display }}</p>
            <p><strong>Entry Hour:</strong> {{ registration.entry_hour|date:"D h a" }}</p>
            <p><strong>Exit Hour:</strong> {{ registration.exit_hour|date:"D h a" }}</p>
            <a href="https://wa.me/{{ attendee.phone|cut:" "|cut:"("|cut:")"|cut:"-"}}?text=Hola%20Ingresa%20a%20la%20aplicacion%20{{ app_url }}">
                <button class="button is-info">Send Token</button>
            </a>
        </div>
        <div class="column is-one-third theme-light">
            <figure class="image is-256x256">
                    {{ qr }}
            </figure>
        </div>
    </div>
    <h2>Following {{ following|length }}/{{ total_active_profiles }}</h2>
    <div class="grid">
        {% for connection in following %}
            <div class="cell">
                {% if connection.followed.attendee.profile_pic %}
                <figure class="image is-128x128">
                    <img src="{{ connection.followed.attendee.profile_pic.url }}" alt="{{  connection.followed.attendee.slug }}">
                </figure>
                {% endif %}
                <p>
                    <a href="{% url 'analytics:attendee-profile' connection.followed.attendee.slug %}">
                        {{ connection.followed.attendee.name }}
                    </a>
                </p>
            </div>
        {% endfor %}
    </div>
    <h2>Followers {{ followers|length }}/{{ total_active_profiles }}</h2>
    <div class="grid">
        {% for connection in followers %}
            <div class="cell">
                {% if connection.followed.attendee.profile_pic %}
                <figure class="image is-128x128">
                    <img src="{{ connection.followed.attendee.profile_pic.url }}" alt="{{  connection.followed.attendee.slug }}">
                </figure>
                {% endif %}
                <p>
                    <a href="{% url 'analytics:attendee-profile' connection.followed.attendee.slug %}">
                        {{ connection.followed.attendee.name }}
                    </a>
                </p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

applications/analytics/templates/analytics/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Los 30 Random de Ma0
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
</head>
<body>
    <section class="section">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </section>
{% block custom_scripts %}

{% endblock %}
</html>

applications/analytics/templates/analytics/leaderboard.html
{% extends 'analytics/base.html' %}
{% block title %}
    Leaderboard
{% endblock %}
{% block content %}
    <h1 class="title">Leaderboard</h1>
    <div class="columns">
    <div class="column">
        <h2>
            Pokemon
        </h2>
        <table>
            <thead>
                <tr>
                    <th>
                        Persona
                    </th>
                    <th>
                        Capturados
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for c in connections %}
                    <tr>
                        <td>
                                {{ c }}

                        </td>
                        <td>
                            {{ c.connections }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="column">
        <h2>
            Sakura
        </h2>
        <table>
            <thead>
            <tr>
                <th>
                    Persona
                </th>
                <th>
                    Capturados
                </th>
            </tr>
            </thead>
            <tbody>
            {% for c in cards %}
                <tr>
                    <td>
                        {{ c }}

                    </td>
                    <td>
                        {{ c.cards }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </div>
{% endblock %}

applications/analytics/templates/analytics/possible_attendees.html
{% extends 'analytics/base.html' %}
{% block title %}
    Posibles asistentes
{% endblock %}
{% block content %}
    <h1 class="title">Possible Attendees</h1>
    <input
          type="text"
          class="input"
          id="myInput"
          onkeyup="myFunction()"
          placeholder="Buscar"
          title="Buscar">
    <table class="table is-fullwidth sortable" id="myTable">
        <thead class="header">
            <tr>
                <th>Name</th>
                <th>Whatsapp</th>
                <th>Instagram</th>
                <th>Profile Pic</th>
            </tr>
        </thead>
        <tbody>
            {% for attendee in possible_attendees %}
                <tr>
                    <td>
                        <a href="{% url 'analytics:attendee-profile' attendee.slug %}">
                            {{ attendee.name }}
                        </a>
                    </td>
                    <td>{{ attendee.phone }}</td>
                    <td>{{ attendee.instagram }}</td>
                    <td>
                        <figure class="image is-128x128">
                            {% if attendee.profile_pic %}
                                <img src="{{ attendee.profile_pic.url }}" alt="{{ attendee.name }}">
                            {% endif %}
                        </figure>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    <script language="javascript">
        const myFunction = () => {
          const trs = document.querySelectorAll('#myTable tr:not(.header)')
          const filter = document.querySelector('#myInput').value
          const regex = new RegExp(filter, 'i')
          const isFoundInTds = td => regex.test(td.innerHTML)
          const isFound = childrenArr => childrenArr.some(isFoundInTds)
          const setTrStyleDisplay = ({ style, children }) => {
            style.display = isFound([
              ...children // <-- All columns
            ]) ? '' : 'none'
          }

          trs.forEach(setTrStyleDisplay)
        }
    </script>
{% endblock %}

applications/analytics/templates/analytics/registration_report.html
{% extends 'analytics/base.html' %}
{% block title %}
    Reporte de registros
{% endblock %}
{% block content %}
    <h1 class="title">Reporte de registros</h1>
    <table class="table is-fullwidth sortable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>+1</th>
                <th>Vegetarian</th>
                <th>Alcohol</th>
                <th>Weed</th>
                <th>Entry Hour</th>
                <th>Exit Hour</th>
            </tr>
        </thead>
        <tbody>
            {% for registration in registrations %}
                <tr>
                    <td>{{ registration.name }}</td>
                    <td>{{ registration.phone }}</td>
                    <td>{{ registration.extra_attendees }}</td>
                    <td>{{ registration.get_vegetarian_display }}</td>
                    <td>{{ registration.get_alcohol_display }}</td>
                    <td>{{ registration.get_weed_display }}</td>
                    <td>{{ registration.entry_hour|date:"D h a" }}</td>
                    <td>{{ registration.exit_hour|date:"D h a" }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block custom_scripts %}
    <script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
{% endblock %}